name: Deploy nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install expect
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: Install nginx via SSH
        run: |
          expect << EOF
          spawn ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@13.93.199.95
          expect "password:"
          send "${{ secrets.SSH_PASSWORD }}\r"
          expect "$ "
          send "sudo apt update\r"
          expect "password for ${{ secrets.SSH_USERNAME }}:"
          send "${{ secrets.SSH_PASSWORD }}\r"
          expect "$ "
          send "sudo apt install -y nginx\r"
          expect "$ "
          send "sudo systemctl start nginx\r"
          expect "$ "
          send "sudo systemctl enable nginx\r"
          expect "$ "
          send "exit\r"
          expect eof
          EOF